In [1]:
pip install pandas nltk

In [2]:
import string
import re
from math import log
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize, word_tokenize
import pandas as pd
from collections import defaultdict
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import nltk
from sklearn.metrics import accuracy_score, classification_report
from nltk.stem import WordNetLemmatizer
import numpy as np

In [3]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [4]:
df = pd.read_csv("/content/LabelledTweets.csv")
df

Class                                             Tweets
0          1  !!! RT @mayasolovely: As a woman you shouldn't...
1          0  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2          0  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3          0  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4          0  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...      ...                                                ...
24778      0  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779      1  you've gone and broke the wrong heart baby, an...
24780      0  young buck wanna eat!!.. dat nigguh like I ain...
24781      0              youu got wild bitches tellin you lies
24782      1  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

[24783 rows x 2 columns]

In [5]:
df.Class.value_counts() #count for hate and neutral speech

0    20620
1     4163
Name: Class, dtype: int64

**Split Dataset into training and testing**

In [6]:
X = df['Tweets']
y = df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

**Bag Of Words**

In [7]:
bow = CountVectorizer(stop_words = 'english')
X_train_bow = bow.fit_transform(X_train.values)
X_train_bow.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [8]:
print(bow.vocabulary_)

{'rt': 22983, 'funsizedyogi': 10848, 'theblackvoice': 26486, 'white': 29293, 'ppl': 21159, 'forget': 10475, 'horrific': 12800, 'past': 20333, 'paint': 20194, 'pretty': 21249, 'picture': 20707, 'ho': 12592, '8230': 1254, 'funny': 10838, 'thing': 26750, 'just': 14850, 'people': 20518, 'doing': 8459, 'seeing': 23638, 'pics': 20705, 'judging': 14778, 'birds': 4146, 'wrong': 29724, 'winksosa': 29477, 'aintshitsweet__': 2210, 'rakwon_ogod': 21905, 'nigga': 19099, 'messed': 17703, 'bitch': 4162, '128557': 426, '128514': 384, 'https': 12891, '5mnxkvayot': 1089, 'th_real_esco': 26380, 'jbrendaro30': 14244, 'zgabrail': 30512, 'ramsin1995': 21931, 'gabeeli8': 10934, 'jacob2times': 14053, 'ass': 2992, 'nigggaaa': 19119, 'real': 22098, 'mia_coop': 17760, 'speaking': 24943, 'time': 26960, 'tryna': 27611, 'make': 17125, 'look': 16642, 'bad': 3370, 'like': 16302, 'wasn': 28911, 'eating': 9042, 'pussy': 21607, 'nah': 18716, 'mimi': 17938, 'domworldpeace': 8510, 'baseball': 3600, 'season': 23603, 'win':

In [9]:
print(bow.get_feature_names_out())
for sentence, feature in zip(X_train, X_train_bow.toarray()):
 print(sentence)
 print(feature)

Streaming output truncated to the last 5000 lines.
[0 0 0 ... 0 0 0]
@moodym0lly back Atcha bitch!
[0 0 0 ... 0 0 0]
got these bad bitches waiting on me
[0 0 0 ... 0 0 0]
Luke Bryan is such a faggot tool
[0 0 0 ... 0 0 0]
But why did this bitch just follow me...don't even like u @_graceexo
[0 0 0 ... 0 0 0]
Am I really going to sit here and cry like a bitch....
[0 0 0 ... 0 0 0]
RT @lilbrownbear330: about to rock this bitch with @weare_golden with our beautiful angelic voices #Gaffeoke
[0 0 0 ... 0 0 0]
Can u say hoe hoe hoe? Ewww she was nasty. I was so mean to her on the daily. I'll spare the details lol.
[0 0 0 ... 0 0 0]
why niggas put heart eyes under everybody pictures? &#128553; then it be them poo la la hoes.
[0 0 0 ... 0 0 0]
Kyles a bitch
[0 0 0 ... 0 0 0]
I'm too nice to people , but when I finally decide to say something , I'm a bitch . wonderful .
[0 0 0 ... 0 0 0]
&#8220;@koleworld4: &#128541; http://t.co/61zY8Cc47j&#8221;bitches swear they emojis&#128553;&#128514;
[0 0 0

In [10]:
bow = CountVectorizer(stop_words = 'english')
X_test_bow = bow.fit_transform(X_test.values)
X_test_bow.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [11]:
print(bow.get_feature_names_out())
for sentence, feature in zip(X_test, X_test_bow.toarray()):
 print(sentence)
 print(feature)

Streaming output truncated to the last 5000 lines.
[0 0 0 ... 0 0 0]
from conversation at that... &#8220;@Blakcocaine_ These hoes be falling too easy. &#128554;&#8221;
[0 0 0 ... 0 0 0]
RT @doddynyc: ya bitches luv throwing bread crumbs on the ground and complain about the pigeons who come flocking towards ya
[0 0 0 ... 0 0 0]
"I fucking hate that bitch so much I wanna smack her in the face then tongue kiss her"
[0 0 0 ... 0 0 0]
@mrfoolycooly i dont think he did the celestial dragon killed him
[0 0 0 ... 0 0 0]
RT @sydneysoleil: Spider-Man was a bitch highkey tho
[0 0 0 ... 0 0 0]
Forgiato Fest in Dallas this year fuck yeah bitch
[0 0 0 ... 0 0 0]
@drrrruuuu @TheChrisCates pussy
[0 0 0 ... 0 0 0]
@Pepper_Redbone @Yankees @Mets Oh yeah. And the annoying damn duck calls?? They outta be banned. Duck horns??
[0 0 0 ... 0 0 0]
RT @cyb3rvibes: &#8220;@SejlaSmajlovic: Funniest one lmfaoooo https://t.co/1WT6BBlIdp&#8221; "swag bitch"
[0 0 0 ... 0 0 0]
I really committed to fucking with the ri

**TF-IDF**

In [12]:
tfidf = TfidfVectorizer(stop_words = 'english')
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.fit_transform(X_test)

In [13]:
print(tfidf.vocabulary_)

{'934': 524, '8616': 504, 'got': 4592, 'missed': 7076, 'yo': 11925, 'bitch': 1608, 'rt': 9047, 'kingtunchi_': 6076, 'fucking': 4285, 'bad': 1297, 'gone': 4560, 'need': 7410, 'money': 7156, 'lil': 6402, 'homie': 5047, 'eanahs__': 3589, '1inkkofrosess': 267, 'lol': 6529, 'credit': 2835, 'ain': 846, 'near': 7404, 'good': 4564, 'know': 6114, 'right': 8902, 'man': 6733, 'job': 5760, 'ho': 5013, 'nice': 7483, 'maxin_betha': 6841, 'wipe': 11652, 'cum': 2914, 'faggot': 3878, '80sbaby4life': 490, 'contact': 2701, 'lens': 6321, 'wildin': 11628, 'shit': 9443, 'niggas': 7508, 'cheat': 2348, 'don': 3401, 'expect': 3822, 'pay': 7988, 'whatsoever': 11554, 'yall': 11862, 'just': 5864, 'naive': 7351, 'bitches': 1610, 'mother': 7202, 'asked': 1143, 'wanted': 11418, 'christmas': 2452, 'year': 11889, 'replied': 8806, 'crazy': 2821, 'sister': 9566, 'real': 8677, 'dedication': 3109, '171': 240, 'arigold_88': 1103, 'diarrhea': 3236, 'shitting': 9451, 'bathroom': 1404, '187': 246, 'kiss': 6086, 'imo': 5355, '

In [14]:
X_train_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
X_test_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
for sentence, feature in zip(X_train, X_train_tfidf):
 print(sentence)
 print(feature)

Streaming output truncated to the last 5000 lines.
  (0, 24022)	0.18955632877951661
  (0, 4162)	0.10188090520017141
Never will we be an item. Psycho bitch!
  (0, 13862)	0.7307035667705387
  (0, 21491)	0.6650733279447104
  (0, 4162)	0.15410959076371844
RT @ajade___: everybody tryna fuck the next nigga bitch not knowin that his bitch is the next nigga bitch &#128586;&#128566;
  (0, 2234)	0.43665687844069334
  (0, 435)	0.40698840297197225
  (0, 15550)	0.38963345736920496
  (0, 449)	0.3426100362977165
  (0, 9586)	0.27186069535586377
  (0, 10731)	0.1680004536406854
  (0, 27611)	0.25481039561161284
  (0, 4162)	0.27628035184529165
  (0, 19099)	0.3491031816302197
  (0, 22983)	0.09607679339285646
Nigga was sweating like a guilty preacher in that bitch
  (0, 21190)	0.5795130931871105
  (0, 11808)	0.5214901749405133
  (0, 25826)	0.5293894918234634
  (0, 16302)	0.19380174337805633
  (0, 4162)	0.12728145579252173
  (0, 19099)	0.24124604346408976
I'm just sitting here waiting for twitter to explode 

In [17]:
for sentence, feaature in zip(X_test, X_test_tfidf):
 print(sentence)
 print(feature)

Streaming output truncated to the last 5000 lines.
All dem colored boys be sayin I dare baby daddy. I gots to protect my semen under da lock and key. And I wrap 2x
  (0, 19352)	0.33429819288639373
  (0, 23376)	0.29027864974749185
  (0, 1250)	0.771736621403033
  (0, 24022)	0.18233702844692584
  (0, 2204)	0.3937650321519706
  (0, 4168)	0.14180239218926668
hoes thinkin 2014 turns them into born again virgins.
  (0, 19352)	0.33429819288639373
  (0, 23376)	0.29027864974749185
  (0, 1250)	0.771736621403033
  (0, 24022)	0.18233702844692584
  (0, 2204)	0.3937650321519706
  (0, 4168)	0.14180239218926668
Dudes probably just think eating pussy is sucking on pussy lips &#128530;
  (0, 19352)	0.33429819288639373
  (0, 23376)	0.29027864974749185
  (0, 1250)	0.771736621403033
  (0, 24022)	0.18233702844692584
  (0, 2204)	0.3937650321519706
  (0, 4168)	0.14180239218926668
RT @_xobrandy: @Blaxxxican invest in some curtains bitch
  (0, 19352)	0.33429819288639373
  (0, 23376)	0.29027864974749185
  (0, 125

**Tokenization**

In [18]:
def tokenize(text):
    tokens = word_tokenize(text)
    return tokens

In [19]:
tokenized = df['Tweets'].apply(tokenize)
print(tokenized)

0        [!, !, !, RT, @, mayasolovely, :, As, a, woman...
1        [!, !, !, !, !, RT, @, mleew17, :, boy, dats, ...
2        [!, !, !, !, !, !, !, RT, @, UrKindOfBrand, Da...
3        [!, !, !, !, !, !, !, !, !, RT, @, C_G_Anderso...
4        [!, !, !, !, !, !, !, !, !, !, !, !, !, RT, @,...
                               ...                        
24778    [you, 's, a, muthaf, *, *, *, in, lie, &, #, 8...
24779    [you, 've, gone, and, broke, the, wrong, heart...
24780    [young, buck, wan, na, eat, !, !, .., dat, nig...
24781        [youu, got, wild, bitches, tellin, you, lies]
24782    [~~Ruffled, |, Ntac, Eileen, Dahlia, -, Beauti...
Name: Tweets, Length: 24783, dtype: object


In [20]:
X_train_tokenized = X_train.apply(tokenize)
print(X_train_tokenized)

15272    [RT, @, FunSizedYogi, :, @, TheBlackVoice, wel...
9351     [Funny, thing, is, ...., it, 's, not, just, th...
20323    [RT, @, winkSOSA, :, ``, @, AintShitSweet__, :...
3638     [@, Jbrendaro30, @, ZGabrail, @, ramsin1995, @...
20579                             [S/o, that, real, bitch]
                               ...                        
21575    [The, last, at-bat, at, Yankee, Stadium, ., Th...
5390     [@, _bradleey, LMFAOOOO, yooo, I, lost, my, el...
860      [#, porn, ,, #, android, ,, #, iphone, ,, #, i...
15795    [RT, @, JennyJohnsonHi5, :, Just, when, I, tho...
23654    [bitches, ain, &, #, 8217, ;, t, shit, ,, and,...
Name: Tweets, Length: 19826, dtype: object


In [21]:
X_test_tokenized = X_test.apply(tokenize)
print(X_test_tokenized)

2281     [934, 8616, i, got, a, missed, call, from, yo,...
15914    [RT, @, KINGTUNCHI_, :, Fucking, with, a, bad,...
18943    [RT, @, eanahS__, :, @, 1inkkofrosess, lol, my...
16407    [RT, @, Maxin_Betha, Wipe, the, cum, out, of, ...
13326    [Niggas, cheat, on, they, bitch, and, do, n't,...
                               ...                        
3310     [@, GrizzboAdams, @, wyattnuckels, haha, ight,...
22759    [When, you, see, kids, being, bad, &, amp, ;, ...
21953                  [This, bitch, done, blew, my, high]
9056            [Fat, Trel, that, niggah, &, #, 128076, ;]
13246    [Neverrr, ,, play, me, for, stupid, because, I...
Name: Tweets, Length: 4957, dtype: object


**Lowercasing**

In [22]:
X_train_tokenized_lower = X_train_tokenized.apply(lambda x: [word.lower() for word in x])
print(X_train_tokenized_lower)

15272    [rt, @, funsizedyogi, :, @, theblackvoice, wel...
9351     [funny, thing, is, ...., it, 's, not, just, th...
20323    [rt, @, winksosa, :, ``, @, aintshitsweet__, :...
3638     [@, jbrendaro30, @, zgabrail, @, ramsin1995, @...
20579                             [s/o, that, real, bitch]
                               ...                        
21575    [the, last, at-bat, at, yankee, stadium, ., th...
5390     [@, _bradleey, lmfaoooo, yooo, i, lost, my, el...
860      [#, porn, ,, #, android, ,, #, iphone, ,, #, i...
15795    [rt, @, jennyjohnsonhi5, :, just, when, i, tho...
23654    [bitches, ain, &, #, 8217, ;, t, shit, ,, and,...
Name: Tweets, Length: 19826, dtype: object


In [23]:
X_test_tokenized_lower = X_test_tokenized.apply(lambda x: [word.lower() for word in x])
print(X_test_tokenized_lower)

2281     [934, 8616, i, got, a, missed, call, from, yo,...
15914    [rt, @, kingtunchi_, :, fucking, with, a, bad,...
18943    [rt, @, eanahs__, :, @, 1inkkofrosess, lol, my...
16407    [rt, @, maxin_betha, wipe, the, cum, out, of, ...
13326    [niggas, cheat, on, they, bitch, and, do, n't,...
                               ...                        
3310     [@, grizzboadams, @, wyattnuckels, haha, ight,...
22759    [when, you, see, kids, being, bad, &, amp, ;, ...
21953                  [this, bitch, done, blew, my, high]
9056            [fat, trel, that, niggah, &, #, 128076, ;]
13246    [neverrr, ,, play, me, for, stupid, because, i...
Name: Tweets, Length: 4957, dtype: object


**Removing Stop Words**

In [24]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [25]:
stopWords = set(stopwords.words('english'))

In [26]:
def remove_stopwords(tokens):
  without_stopwords = [word for word in tokens if word not in stopWords]
  return without_stopwords

In [27]:
X_train_without_stopwords = X_train_tokenized_lower.apply(remove_stopwords)
print(X_train_without_stopwords)

15272    [rt, @, funsizedyogi, :, @, theblackvoice, wel...
9351     [funny, thing, ...., 's, people, ., 's, people...
20323    [rt, @, winksosa, :, ``, @, aintshitsweet__, :...
3638     [@, jbrendaro30, @, zgabrail, @, ramsin1995, @...
20579                                   [s/o, real, bitch]
                               ...                        
21575    [last, at-bat, yankee, stadium, ., thanks, mak...
5390     [@, _bradleey, lmfaoooo, yooo, lost, elevator,...
860      [#, porn, ,, #, android, ,, #, iphone, ,, #, i...
15795    [rt, @, jennyjohnsonhi5, :, thought, justin, b...
23654    [bitches, &, #, 8217, ;, shit, ,, &, #, 8217, ...
Name: Tweets, Length: 19826, dtype: object


In [28]:
X_test_without_stopwords = X_test_tokenized_lower.apply(remove_stopwords)
print(X_test_without_stopwords)

2281             [934, 8616, got, missed, call, yo, bitch]
15914    [rt, @, kingtunchi_, :, fucking, bad, bitch, g...
18943    [rt, @, eanahs__, :, @, 1inkkofrosess, lol, cr...
16407    [rt, @, maxin_betha, wipe, cum, faggot, rt, @,...
13326    [niggas, cheat, bitch, n't, expect, pay, back,...
                               ...                        
3310     [@, grizzboadams, @, wyattnuckels, haha, ight,...
22759    [see, kids, bad, &, amp, ;, parents, standing,...
21953                            [bitch, done, blew, high]
9056                  [fat, trel, niggah, &, #, 128076, ;]
13246    [neverrr, ,, play, stupid, 'm, far, .., bitche...
Name: Tweets, Length: 4957, dtype: object


**Smoothing**

In [29]:
def laplace_smoothing(tokens):
    # Create a frequency dictionary for words in tokens
    word_counts = defaultdict(int)
    for word in tokens:
        word_counts[word] += 1

    # Define the vocabulary size (number of unique words)
    vocabulary_size = len(word_counts)

    # Add 1 to the count of each word in the vocabulary
    smoothed_word_counts = {word: count + 1 for word, count in word_counts.items()}

    # Calculate probabilities for each word
    word_probabilities = {word: count / (len(tokens) + vocabulary_size) for word, count in smoothed_word_counts.items()}
    return word_probabilities

    # add-one smoothing to ensure that no word has a zero probability of occurring.

In [30]:
X_train_smoothed_probabilities = X_train_without_stopwords.apply(laplace_smoothing)
print(X_train_smoothed_probabilities)

15272    {'rt': 0.044444444444444446, '@': 0.0666666666...
9351     {'funny': 0.07692307692307693, 'thing': 0.0769...
20323    {'rt': 0.018018018018018018, '@': 0.0450450450...
3638     {'@': 0.2727272727272727, 'jbrendaro30': 0.090...
20579    {'s/o': 0.3333333333333333, 'real': 0.33333333...
                               ...                        
21575    {'last': 0.058823529411764705, 'at-bat': 0.058...
5390     {'@': 0.034482758620689655, '_bradleey': 0.034...
860      {'#': 0.1702127659574468, 'porn': 0.0425531914...
15795    {'rt': 0.047619047619047616, '@': 0.0476190476...
23654    {'bitches': 0.07692307692307693, '&': 0.153846...
Name: Tweets, Length: 19826, dtype: object


In [31]:
X_test_smoothed_probabilities = X_test_without_stopwords.apply(laplace_smoothing)
print(X_test_smoothed_probabilities)

2281     {'934': 0.14285714285714285, '8616': 0.1428571...
15914    {'rt': 0.07692307692307693, '@': 0.07692307692...
18943    {'rt': 0.046511627906976744, '@': 0.0697674418...
16407    {'rt': 0.1, '@': 0.1, 'maxin_betha': 0.0666666...
13326    {'niggas': 0.08, 'cheat': 0.08, 'bitch': 0.08,...
                               ...                        
3310     {'@': 0.17647058823529413, 'grizzboadams': 0.1...
22759    {'see': 0.044444444444444446, 'kids': 0.044444...
21953    {'bitch': 0.25, 'done': 0.25, 'blew': 0.25, 'h...
9056     {'fat': 0.14285714285714285, 'trel': 0.1428571...
13246    {'neverrr': 0.06896551724137931, ',': 0.068965...
Name: Tweets, Length: 4957, dtype: object


**Normalization**

In [32]:
def normalization(tokens):
  text = ' '.join(tokens)
  punctuation = re.sub(r'[^\w\s]','',text)
  return punctuation

In [33]:
X_train_without_punctuation = X_train_tokenized.apply(normalization)
print(X_train_without_punctuation)

15272    RT  FunSizedYogi   TheBlackVoice well how else...
9351     Funny thing is  it s not just the people doing...
20323    RT  winkSOSA    AintShitSweet__    Rakwon_OGOD...
3638      Jbrendaro30  ZGabrail  ramsin1995  GabeEli8  ...
20579                                   So that real bitch
                               ...                        
21575    The last atbat at Yankee Stadium  Thanks for m...
5390      _bradleey LMFAOOOO yooo I lost my elevator pa...
860       porn   android   iphone   ipad   sex   xxx   ...
15795    RT  JennyJohnsonHi5  Just when I thought Justi...
23654    bitches ain   8217  t shit  and they ain   821...
Name: Tweets, Length: 19826, dtype: object


In [34]:
X_test_without_punctuation = X_test_tokenized.apply(normalization)
print(X_test_without_punctuation)

2281            934 8616 i got a missed call from yo bitch
15914    RT  KINGTUNCHI_  Fucking with a bad bitch you ...
18943    RT  eanahS__   1inkkofrosess lol my credit ai ...
16407    RT  Maxin_Betha Wipe the cum out of them faggo...
13326    Niggas cheat on they bitch and do nt expect no...
                               ...                        
3310      GrizzboAdams  wyattnuckels haha ight nig calm...
22759    When you see kids being bad  amp  their parent...
21953                         This bitch done blew my high
9056                        Fat Trel that niggah   128076 
13246    Neverrr  play me for stupid because I m far fr...
Name: Tweets, Length: 4957, dtype: object


**Stemming**

In [35]:
def PorterStemming(tokens):
    porterStemmer = nltk.stem.PorterStemmer()
    stemmed = [porterStemmer.stem(word) for word in tokens]
    return stemmed

In [36]:
X_train_stemming = X_train_without_stopwords.apply(PorterStemming)
print(X_train_stemming)

15272    [rt, @, funsizedyogi, :, @, theblackvoic, well...
9351     [funni, thing, ...., 's, peopl, ., 's, peopl, ...
20323    [rt, @, winksosa, :, ``, @, aintshitsweet__, :...
3638     [@, jbrendaro30, @, zgabrail, @, ramsin1995, @...
20579                                   [s/o, real, bitch]
                               ...                        
21575    [last, at-bat, yanke, stadium, ., thank, make,...
5390     [@, _bradleey, lmfaoooo, yooo, lost, elev, pas...
860      [#, porn, ,, #, android, ,, #, iphon, ,, #, ip...
15795    [rt, @, jennyjohnsonhi5, :, thought, justin, b...
23654    [bitch, &, #, 8217, ;, shit, ,, &, #, 8217, ;,...
Name: Tweets, Length: 19826, dtype: object


In [37]:
X_test_stemming = X_test_without_stopwords.apply(PorterStemming)
print(X_test_stemming)

2281               [934, 8616, got, miss, call, yo, bitch]
15914    [rt, @, kingtunchi_, :, fuck, bad, bitch, gone...
18943    [rt, @, eanahs__, :, @, 1inkkofrosess, lol, cr...
16407    [rt, @, maxin_betha, wipe, cum, faggot, rt, @,...
13326    [nigga, cheat, bitch, n't, expect, pay, back, ...
                               ...                        
3310     [@, grizzboadam, @, wyattnuckel, haha, ight, n...
22759    [see, kid, bad, &, amp, ;, parent, stand, &, a...
21953                            [bitch, done, blew, high]
9056                  [fat, trel, niggah, &, #, 128076, ;]
13246    [neverrr, ,, play, stupid, 'm, far, .., bitch,...
Name: Tweets, Length: 4957, dtype: object


**Lemmatization**

In [38]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [39]:
lemmatizer = WordNetLemmatizer()
def lemmatization(tokens):
    lemmatized = [lemmatizer.lemmatize(token) for token in tokens]
    return lemmatized

In [40]:
X_train_lemmatized = X_train_without_stopwords.apply(lemmatization)
print(X_train_lemmatized)

15272    [rt, @, funsizedyogi, :, @, theblackvoice, wel...
9351     [funny, thing, ...., 's, people, ., 's, people...
20323    [rt, @, winksosa, :, ``, @, aintshitsweet__, :...
3638     [@, jbrendaro30, @, zgabrail, @, ramsin1995, @...
20579                                   [s/o, real, bitch]
                               ...                        
21575    [last, at-bat, yankee, stadium, ., thanks, mak...
5390     [@, _bradleey, lmfaoooo, yooo, lost, elevator,...
860      [#, porn, ,, #, android, ,, #, iphone, ,, #, i...
15795    [rt, @, jennyjohnsonhi5, :, thought, justin, b...
23654    [bitch, &, #, 8217, ;, shit, ,, &, #, 8217, ;,...
Name: Tweets, Length: 19826, dtype: object


In [41]:
X_test_lemmatized = X_test_without_stopwords.apply(lemmatization)
print(X_test_lemmatized)

2281             [934, 8616, got, missed, call, yo, bitch]
15914    [rt, @, kingtunchi_, :, fucking, bad, bitch, g...
18943    [rt, @, eanahs__, :, @, 1inkkofrosess, lol, cr...
16407    [rt, @, maxin_betha, wipe, cum, faggot, rt, @,...
13326    [nigga, cheat, bitch, n't, expect, pay, back, ...
                               ...                        
3310     [@, grizzboadams, @, wyattnuckels, haha, ight,...
22759    [see, kid, bad, &, amp, ;, parent, standing, &...
21953                            [bitch, done, blew, high]
9056                  [fat, trel, niggah, &, #, 128076, ;]
13246    [neverrr, ,, play, stupid, 'm, far, .., bitch,...
Name: Tweets, Length: 4957, dtype: object


**Logistic Regression**

In [76]:
class Logistic_Regression():
    def __init__(self, learning_rate, iter_num):
        self.learning_rate = learning_rate
        self.iter_num = iter_num
        self.weight = None
        self.bias = None

    def fit(self, X, y):
        self.rows, self.columns = X.shape
        self.weight = np.zeros(self.columns)
        self.bias = 0
        self.X = X
        self.y = y
        for i in range(self.iter_num):
            self.update_weights()

    def update_weights(self):
        Y_hat = 1 / (1 + np.exp(- (self.X.dot(self.weight) + self.bias)))
        dw = (1 / self.rows) * np.dot(self.X.T, (Y_hat - self.y))
        db = (1 / self.rows) * np.sum(Y_hat - self.y)
        self.weight = self.weight - self.learning_rate * dw
        self.bias = self.bias - self.learning_rate * db

    def predict(self, X):
        Y_pred = 1 / (1 + np.exp(- (X.dot(self.weight) + self.bias)))
        Y_pred = np.where(Y_pred > 0.5, 1, 0)
        return Y_pred

In [77]:
classifier_bow = Logistic_Regression(learning_rate = 0.01, iter_num = 1000)

In [78]:
classifier_tfidf = Logistic_Regression(learning_rate = 0.01, iter_num = 1000)

In [79]:
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)
classifier_bow.fit(X_train_bow.toarray(), y_train) # training logistic regression model using bow representation

In [80]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)
classifier_tfidf.fit(X_train_tfidf.toarray(), y_train) # training logistic regression model using tfidf representation

In [81]:
predictions_bow = classifier_bow.predict(X_test_bow.toarray())

In [82]:
predictions_tfidf = classifier_tfidf.predict(X_test_tfidf.toarray())

In [89]:
classification_report_bow = classification_report(y_test, predictions_bow, target_names=['hate speech', 'neutral text'], zero_division = 1)
print("Classification Report (BOW representation):\n", classification_report_bow)


Classification Report (BOW representation):
               precision    recall  f1-score   support

 hate speech       0.83      1.00      0.91      4122
neutral text       1.00      0.00      0.00       835

    accuracy                           0.83      4957
   macro avg       0.92      0.50      0.45      4957
weighted avg       0.86      0.83      0.76      4957



In [86]:
classification_report_tfidf = classification_report(y_test, predictions_tfidf, target_names=['hate speech', 'neutral text'], zero_division = 1)
print("Classification Report (TF-IDF representation):\n", classification_report_tfidf)

Classification Report (TF-IDF representation):
               precision    recall  f1-score   support

 hate speech       0.83      1.00      0.91      4122
neutral text       1.00      0.00      0.00       835

    accuracy                           0.83      4957
   macro avg       0.92      0.50      0.45      4957
weighted avg       0.86      0.83      0.76      4957

